//
// GENERATED by KVision
//
package com.fonrouge.fslib.services

import io.kvision.remote.HttpMethod
import io.kvision.remote.KVServiceManager

expect class PingService : IPingService

object PingServiceManager : KVServiceManager<PingService>(PingService::class) {
    init {
        bind(IPingService::ping, HttpMethod.POST, null)
    }
}
