//
// GENERATED by KVision
//
package com.fonrouge.fslib.services

import io.kvision.remote.HttpMethod
import io.kvision.remote.KVServiceManager

expect class RegisterProfileService : IRegisterProfileService

object RegisterProfileServiceManager : KVServiceManager<RegisterProfileService>(RegisterProfileService::class) {
    init {
        bind(IRegisterProfileService::registerProfile, HttpMethod.POST, null)
    }
}
