package com.fonrouge.fsLib.common

import com.fonrouge.fsLib.lib.toast
import com.fonrouge.fsLib.model.apiData.CallType
import com.fonrouge.fsLib.model.apiData.CrudTask
import com.fonrouge.fsLib.model.apiData.IApiFilter
import com.fonrouge.fsLib.model.base.BaseDoc
import com.fonrouge.fsLib.model.state.ItemState
import io.kvision.modal.Confirm
import io.kvision.modal.ModalSize
import io.kvision.remote.KVServiceManager
import io.kvision.toast.Toast

/**
 * Displays a confirmation modal and performs a delete operation for a specific item in the API.
 *
 * @param T The type of the item being operated on, which must extend BaseDoc.
 * @param ID The type of the item's ID, which must be a non-nullable type.
 * @param FILT The type of the API filter, which must extend IApiFilter.
 * @param serviceManager An instance of KVServiceManager used to manage the backend service call.
 * @param apiItemFun The function representing the API endpoint for the requested action.
 * @param item The item to be deleted.
 * @param apiFilter An optional filter of type FILT to apply additional conditions to the query. Defaults to an instance generated by apiFilterInstance().
 * @param onFail A lambda function invoked when the delete action fails, receiving the resulting ItemState of type T.
 * @param onSuccess A lambda function invoked when the delete action is successful.
 */
fun <T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>> ICommonContainer<T, ID, FILT>.confirmDeleteView(
    serviceManager: KVServiceManager<*>,
    apiItemFun: Function<*>,
    item: T,
    apiFilter: FILT = apiFilterInstance(),
    onFail: ((ItemState<T>) -> Unit)? = null,
    onSuccess: (() -> Unit)? = null,
) {
    callItemService(
        serviceManager = serviceManager,
        apiItemFun = apiItemFun,
        crudTask = CrudTask.Delete,
        callType = CallType.Query,
        id = item._id,
        item = item,
        apiFilter = apiFilter,
    ) { itemState ->
        if (itemState.hasError.not()) {
            val modal = Confirm(
                caption = "Please Confirm",
                text = "<b>Delete</b> '<i>${labelItem}</i>', id: <b>${
                    labelIdFunc(item)
                }</b> ?",
                rich = true,
                size = ModalSize.XLARGE,
                centered = true,
                noTitle = "Cancel",
                noCallback = {
                    Toast.warning("Delete canceled")
                },
                yesCallback = {
                    callItemService(
                        serviceManager = serviceManager,
                        apiItemFun = apiItemFun,
                        crudTask = CrudTask.Delete,
                        callType = CallType.Action,
                        id = item._id,
                        item = item,
                        apiFilter = apiFilter,
                    ) { itemState1 ->
                        if (itemState1.hasError.not()) {
                            Toast.success(
                                message = itemState1.msgOk ?: "Delete action successful ...",
                            )
                            onSuccess?.invoke()
                        } else {
                            Toast.warning(
                                message = itemState1.msgError ?: "Delete action failed ...",
                            )
                            onFail?.invoke(itemState1)
                        }
                        itemState1
                    }
                }
            )
            modal.show()
        } else {
            itemState.toast()
            onFail?.invoke(itemState)
        }
        itemState
    }
}
