[versions]
exposedCore = "0.61.0"
fsLib = "6.1.1"
h2 = "2.2.224"
jtds = "1.3.1"
junit = "4.13.2"
kiluaRpcVersion = "0.0.45"
kmongo = "5.6.0"
kotlin = "2.4.0"
kotlinxCoroutines = "1.11.0"
kotlinxDatetime = "0.6.1"
kotlinxHtml = "0.12.0"
kspVersion = "2.3.9"
ktor = "3.4.0"
kvision = "9.6.0"
logbackClassic = "1.5.20"
mockk = "1.13.13"
mssqlJdbc = "9.4.1.jre8"
serialization = "1.11.0"
testcontainers = "1.20.4"

[libraries]
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposedCore" }
exposed-dao = { module = "org.jetbrains.exposed:exposed-dao", version.ref = "exposedCore" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposedCore" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposedCore" }
h2 = { module = "com.h2database:h2", version.ref = "h2" }
jtds = { module = "net.sourceforge.jtds:jtds", version.ref = "jtds" }
junit = { module = "junit:junit", version.ref = "junit" }
kilua-rpc-ktor = { module = "dev.kilua:kilua-rpc-ktor", version.ref = "kiluaRpcVersion" }
kilua-rpc-ktor-koin = { module = "dev.kilua:kilua-rpc-ktor-koin", version.ref = "kiluaRpcVersion" }
kmongo-coroutine-serialization = { module = "org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo" }
kmongo-id = { module = "org.litote.kmongo:kmongo-id", version.ref = "kmongo" }
kmongo-id-serialization = { module = "org.litote.kmongo:kmongo-id-serialization", version.ref = "kmongo" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-datetime-jvm = { module = "org.jetbrains.kotlinx:kotlinx-datetime-jvm", version.ref = "kotlinxDatetime" }
kotlinx-html = { module = "org.jetbrains.kotlinx:kotlinx-html", version.ref = "kotlinxHtml" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }
ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-encoding = { module = "io.ktor:ktor-client-encoding", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-network-tls-certificates = { module = "io.ktor:ktor-network-tls-certificates", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-auth = { module = "io.ktor:ktor-server-auth", version.ref = "ktor" }
ktor-server-auth-jwt = { module = "io.ktor:ktor-server-auth-jwt", version.ref = "ktor" }
ktor-server-auto-head-response = { module = "io.ktor:ktor-server-auto-head-response", version.ref = "ktor" }
ktor-server-call-logging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktor-server-compression = { module = "io.ktor:ktor-server-compression", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktor-server-default-headers = { module = "io.ktor:ktor-server-default-headers", version.ref = "ktor" }
ktor-server-forwarded-header = { module = "io.ktor:ktor-server-forwarded-header", version.ref = "ktor" }
ktor-server-html-builder = { module = "io.ktor:ktor-server-html-builder", version.ref = "ktor" }
ktor-server-http-redirect = { module = "io.ktor:ktor-server-http-redirect", version.ref = "ktor" }
ktor-server-netty = { module = "io.ktor:ktor-server-netty", version.ref = "ktor" }
ktor-server-partial-content = { module = "io.ktor:ktor-server-partial-content", version.ref = "ktor" }
ktor-server-sessions = { module = "io.ktor:ktor-server-sessions", version.ref = "ktor" }
ktor-server-status-pages = { module = "io.ktor:ktor-server-status-pages", version.ref = "ktor" }
kvision = { module = "io.kvision:kvision", version.ref = "kvision" }
kvision-common-remote = { module = "io.kvision:kvision-common-remote", version.ref = "kvision" }
kvision-bootstrap = { module = "io.kvision:kvision-bootstrap", version.ref = "kvision" }
kvision-bootstrap-icons = { module = "io.kvision:kvision-bootstrap-icons", version.ref = "kvision" }
kvision-bootstrap-upload = { module = "io.kvision:kvision-bootstrap-upload", version.ref = "kvision" }
kvision-chart = { module = "io.kvision:kvision-chart", version.ref = "kvision" }
kvision-datetime = { module = "io.kvision:kvision-datetime", version.ref = "kvision" }
kvision-fontawesome = { module = "io.kvision:kvision-fontawesome", version.ref = "kvision" }
kvision-i18n = { module = "io.kvision:kvision-i18n", version.ref = "kvision" }
kvision-imask = { module = "io.kvision:kvision-imask", version.ref = "kvision" }
kvision-jquery = { module = "io.kvision:kvision-jquery", version.ref = "kvision" }
kvision-material = { module = "io.kvision:kvision-material", version.ref = "kvision" }
kvision-pace = { module = "io.kvision:kvision-pace", version.ref = "kvision" }
kvision-print = { module = "io.kvision:kvision-print", version.ref = "kvision" }
kvision-react = { module = "io.kvision:kvision-react", version.ref = "kvision" }
kvision-redux-kotlin = { module = "io.kvision:kvision-redux-kotlin", version.ref = "kvision" }
kvision-rest = { module = "io.kvision:kvision-rest", version.ref = "kvision" }
kvision-richtext = { module = "io.kvision:kvision-richtext", version.ref = "kvision" }
kvision-routing-navigo-ng = { module = "io.kvision:kvision-routing-navigo-ng", version.ref = "kvision" }
kvision-state = { module = "io.kvision:kvision-state", version.ref = "kvision" }
kvision-tabulator = { module = "io.kvision:kvision-tabulator", version.ref = "kvision" }
kvision-tabulator-remote = { module = "io.kvision:kvision-tabulator-remote", version.ref = "kvision" }
kvision-testutils = { module = "io.kvision:kvision-testutils", version.ref = "kvision" }
kvision-toastify = { module = "io.kvision:kvision-toastify", version.ref = "kvision" }
kvision-tom-select = { module = "io.kvision:kvision-tom-select", version.ref = "kvision" }
kvision-tom-select-remote = { module = "io.kvision:kvision-tom-select-remote", version.ref = "kvision" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logbackClassic" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
mssql-jdbc = { module = "com.microsoft.sqlserver:mssql-jdbc", version.ref = "mssqlJdbc" }
testcontainers-mongodb = { module = "org.testcontainers:mongodb", version.ref = "testcontainers" }

[plugins]
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }
kilua-rpc = { id = "dev.kilua.rpc", version.ref = "kiluaRpcVersion" }
kvision = { id = "io.kvision", version.ref = "kvision" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
