package com.fonrouge.fsLib.model.apiData

import com.fonrouge.fsLib.model.base.BaseDoc
import com.fonrouge.fsLib.types.ApplicationCall

/**
 * Sealed class representing various API items used to perform CRUD operations.
 *
 * This class hierarchy distinguishes between `Query` operations (which typically use an ID)
 * and `Action` operations (which carry a full data payload).
 *
 * @param T The type of the specific document being processed.
 * @param ID The type of the identifier for the specific document.
 * @param FILT The type of filter applied during API operations.
 */
sealed class ApiItem<T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>> {
    /** The type of the API call, e.g., Query or Action. */
    abstract val callType: CallType

    /** The specific CRUD task to be performed, e.g., Create, Read, Update, Delete. */
    abstract val crudTask: CrudTask

    /** The filter criteria to be applied to the API operation. */
    abstract val apiFilter: FILT

    /** The optional application call context, typically used on the server side. */
    abstract val call: ApplicationCall?

    /**
     * Represents a query-based API operation, which typically involves an ID and filter criteria.
     * These are often used to request data or to specify which item to act upon without sending the full data payload.
     */
    sealed class Query<T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>> : ApiItem<T, ID, FILT>() {
        /** The unique identifier of the document being queried. Can be null for creation queries. */
        abstract val id: ID?

        /** The type of the API call, fixed to [CallType.Query]. */
        override val callType: CallType = CallType.Query

        /**
         * Represents a query to create a new document.
         *
         * @property id The ID of the document to be created, often null if the ID is generated by the server.
         * @property apiFilter The filter criteria for the operation.
         * @property call The optional application call context.
         */
        data class Create<T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>>(
            override val id: ID? = null,
            override val apiFilter: FILT,
            override val call: ApplicationCall? = null,
        ) : Query<T, ID, FILT>() {
            /** The CRUD task, fixed to [CrudTask.Create]. */
            override val crudTask: CrudTask = CrudTask.Create
        }

        /**
         * Represents a query to read an existing document.
         *
         * @property id The unique identifier of the document to read.
         * @property apiFilter The filter criteria for the operation.
         * @property call The optional application call context.
         */
        data class Read<T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>>(
            override val id: ID,
            override val apiFilter: FILT,
            override val call: ApplicationCall? = null,
        ) : Query<T, ID, FILT>() {
            /** The CRUD task, fixed to [CrudTask.Read]. */
            override val crudTask: CrudTask = CrudTask.Read
        }

        /**
         * Represents a query to update an existing document.
         *
         * @property id The unique identifier of the document to update.
         * @property apiFilter The filter criteria for the operation.
         * @property call The optional application call context.
         */
        data class Update<T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>>(
            override val id: ID,
            override val apiFilter: FILT,
            override val call: ApplicationCall? = null,
        ) : Query<T, ID, FILT>() {
            /** The CRUD task, fixed to [CrudTask.Update]. */
            override val crudTask: CrudTask = CrudTask.Update
        }

        /**
         * Represents a query to delete an existing document.
         *
         * @property id The unique identifier of the document to delete.
         * @property apiFilter The filter criteria for the operation.
         * @property call The optional application call context.
         */
        data class Delete<T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>>(
            override val id: ID,
            override val apiFilter: FILT,
            override val call: ApplicationCall? = null,
        ) : Query<T, ID, FILT>() {
            /** The CRUD task, fixed to [CrudTask.Delete]. */
            override val crudTask: CrudTask = CrudTask.Delete
        }
    }

    /**
     * Represents an action-based API operation, which includes the full data payload (`item`).
     * These are used when creating, updating, or deleting a document.
     */
    sealed class Action<T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>> : ApiItem<T, ID, FILT>() {
        /** The document instance involved in the action. */
        abstract val item: T

        /** The type of the API call, fixed to [CallType.Action]. */
        override val callType: CallType = CallType.Action

        /** A corresponding [Query] representation of this action. */
        abstract val asQuery: ApiItem<T, ID, FILT>

        /**
         * Represents an action to create a new document.
         *
         * @property item The document to be created.
         * @property apiFilter The filter criteria for the operation.
         * @property call The optional application call context.
         */
        data class Create<T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>>(
            override val item: T,
            override val apiFilter: FILT,
            override val call: ApplicationCall? = null,
        ) : Action<T, ID, FILT>() {
            /** The CRUD task, fixed to [CrudTask.Create]. */
            override val crudTask: CrudTask = CrudTask.Create

            /** Converts this action into a [Query.Create] object. */
            override val asQuery: Query<T, ID, FILT>
                get() = Query.Create(
                    id = item._id,
                    apiFilter = apiFilter,
                    call = call
                )
        }

        /**
         * Represents an action to update an existing document.
         *
         * @property item The document with the updated data.
         * @property apiFilter The filter criteria for the operation.
         * @property call The optional application call context.
         */
        data class Update<T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>>(
            override val item: T,
            override val apiFilter: FILT,
            override val call: ApplicationCall? = null,
        ) : Action<T, ID, FILT>() {
            /** The CRUD task, fixed to [CrudTask.Update]. */
            override val crudTask: CrudTask = CrudTask.Update

            /** Converts this action into a [Query.Update] object. */
            override val asQuery: Query<T, ID, FILT>
                get() = Query.Update(
                    id = item._id,
                    apiFilter = apiFilter,
                    call = call
                )
        }

        /**
         * Represents an action to delete an existing document.
         *
         * @property item The document to be deleted.
         * @property apiFilter The filter criteria for the operation.
         * @property call The optional application call context.
         */
        class Delete<T : BaseDoc<ID>, ID : Any, FILT : IApiFilter<*>>(
            override val item: T,
            override val apiFilter: FILT,
            override val call: ApplicationCall? = null,
        ) : Action<T, ID, FILT>() {
            /** The CRUD task, fixed to [CrudTask.Delete]. */
            override val crudTask: CrudTask = CrudTask.Delete

            /** Converts this action into a [Query.Delete] object. */
            override val asQuery: Query<T, ID, FILT>
                get() = Query.Delete(
                    id = item._id,
                    apiFilter = apiFilter,
                    call = call
                )
        }
    }
}
