package com.fonrouge.fullStack.config

import com.fonrouge.base.api.IApiFilter
import com.fonrouge.base.common.ICommon
import com.fonrouge.fullStack.lib.disposeOnHidden
import com.fonrouge.fullStack.lib.UrlParams
import com.fonrouge.fullStack.lib.encodeURIComponent
import com.fonrouge.fullStack.config.ConfigViewContainer.VMode
import com.fonrouge.fullStack.view.View
import io.kvision.modal.Modal
import io.kvision.modal.ModalSize
import io.kvision.utils.createInstance
import kotlinx.browser.window
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json
import kotlin.reflect.KClass
import kotlin.reflect.createInstance

/**
 * Abstract class that represents a configuration view for managing connections between common containers,
 * views, and API filters. This class provides utility methods for URL management and API filter handling.
 *
 * @param V The type of the associated view.
 * @param FILT The type of the API filter.
 * @property commonContainer The common container defining shared data, filter serializers, and properties such as labels.
 * @property viewKClass The Kotlin class reference for the associated view.
 * @property _baseUrl The optional base URL for this configuration view.
 */
abstract class ConfigView<V : View<FILT>, FILT : IApiFilter<*>>(
    open val commonContainer: ICommon<FILT>,
    val viewKClass: KClass<out V>,
    @Suppress("PropertyName") internal val _baseUrl: String? = null,
) {
    open val baseUrl: String
        get() {
            return _baseUrl ?: "View${commonContainer.name}"
        }

    companion object {
        /**
         * Map of general view configurations. Delegated to [ViewRegistry].
         */
        val configViewMap get() = ViewRegistry.configViewMap

        /**
         * Represents the default mode of displaying the view list in the application.
         * This variable is initialized with the `modal` value of the `VMode` enum,
         * indicating that the view list will be shown in a modal window by default.
         */
        var defaultViewMode: VMode = VMode.modal
    }

    val url: String get() = "#/" + this.baseUrl
    open val label: String get() = commonContainer.label
    open val labelUrl: Pair<String, String> get() = label to url

    /**
     * Navigates to the desired view based on the provided API filter and viewing mode.
     *
     * This method delegates to the `openView` function to display the view either in a new browser context
     * (e.g., a new tab or window) or as a modal dialog, depending on the specified `vmode`.
     *
     * @param apiFilter The filter criteria used to configure the view list. Default is an instance of the API filter
     *                  generated by `commonContainer.apiFilterInstance()`.
     * @param vmode The viewing mode that determines how the view list should be displayed.
     *              Supported modes include `_blank`, `_self`, `_parent`, `_top`, and `modal`.
     *              The default is `defaultVMode`.
     */
    @Suppress("unused")
    fun navigateToView(
        apiFilter: FILT = commonContainer.apiFilterInstance(),
        vmode: VMode = defaultViewMode
    ) = openView(apiFilter, vmode)

    /**
     * Creates a new instance of the view and initializes it with the provided URL parameters and initialization logic.
     *
     * @param urlParams The optional URL parameters to be associated with the new view instance. If not provided, default URL parameters are used.
     * @param init An optional lambda function used to initialize the view instance after its creation.
     * @return A newly created view instance of type [V], configured with the provided parameters and initialization logic.
     */
    @OptIn(ExperimentalJsReflectionCreateInstance::class)
    fun newViewInstance(urlParams: UrlParams?, init: (V.() -> Unit)? = null): V {
        val v1: V = viewKClass.createInstance()
        // TODO: find out why are differences between js.createInstance() and kotlin.reflect.createInstance() in development mode vs production mode
        val v: V = if (js("typeof v1") == "object") {
//            console.warn("using kotlin.reflect.createInstance() instead of js.createInstanceHack() for ${viewKClass.simpleName}")
            v1
        } else {
//            console.warn("using js.createInstanceHack().unsafeCast<V> for ${viewKClass.simpleName}")
            viewKClass.js.createInstance()
        }
//        console.warn("v", v)
        return v.apply {
            this.urlParams = urlParams ?: UrlParams()
            apiFilterFromUrl?.let {
                apiFilter = it
            }
            init?.invoke(this)
        }
    }

    /**
     * Opens the view list based on the specified API filter and viewing mode.
     *
     * Depending on the selected [vmode], the view list can be opened in a new browser target (e.g., new tab or window)
     * or displayed in a modal dialog. If a modal dialog is chosen, a new view instance is created and displayed.
     *
     * @param apiFilter The filter criteria used to configure the view list.
     * @param vmode The viewing mode that determines how the view list should be displayed.
     *              Supported modes include `_blank`, `_self`, `_parent`, `_top`, and `modal`.
     */
    @Suppress("unused")
    fun openView(apiFilter: FILT = commonContainer.apiFilterInstance(), vmode: VMode = defaultViewMode) {
        when (vmode) {
            VMode._blank,
            VMode._self,
            VMode._parent,
            VMode._top -> window.open(url = viewUrl(apiFilter = apiFilter), target = "$vmode")

            VMode.modal -> {
                val modal = Modal(
                    caption = "",
                    size = ModalSize.XLARGE,
                    animation = false,
                    centered = false,
                    className = "viewListModal"
                ) {
                    newViewInstance(UrlParams(apiFilterParam(apiFilter))).apply {
                        viewModal = this@Modal
                        startDisplayPage()
                    }
                }
                modal.show()
                modal.disposeOnHidden()
            }
        }
    }

    /**
     * builds a single pair of key=value url parameter
     */
    @Suppress("unused")
    inline fun <reified T> pairParam(key: String, obj: T): Pair<String, String> =
        key to Json.encodeToString(obj)

    fun <T> pairParam(key: String, serializer: KSerializer<T>, obj: T): Pair<String, String> =
        key to Json.encodeToString(serializer, obj)

    /**
     * Generates a pair representing the label and its associated URL based on the current configuration.
     *
     * If the instance is of type `ConfigViewList`, a specialized view list URL is constructed.
     * Otherwise, a general URL including API filter parameters is created.
     *
     * @param apiFilter The API filter instance used to build the URL. Defaults to the result of `commonContainer.apiFilterInstance()`.
     * @return A `Pair` containing the label as the first value and the constructed URL as the second value.
     */
    open fun toLabelUrlPair(
        apiFilter: FILT = commonContainer.apiFilterInstance()
    ): Pair<String, String> = label to viewUrl(apiFilter)

    /**
     * builds an url with a list key=value url parameters
     */
    fun urlWithParams(vararg pairParams: Pair<String, String>): String = if (pairParams.isNotEmpty()) {
        val result = StringBuilder(url)
        pairParams.forEachIndexed { i, s ->
            result.append(if (i == 0) "?" else "&")
            result.append("${s.first}=${encodeURIComponent(s.second)}")
        }
        result.toString()
    } else {
        url
    }

    /**
     * Generates a URL with parameters based on the provided API filter.
     *
     * This method combines the API filter parameter and constructs a URL with key-value query parameters
     * appended to the base URL. It uses the default API filter instance if no filter is provided as an argument.
     *
     * @param apiFilter The filter criteria used to configure the URL parameters. Defaults to an instance generated
     *                  by `commonContainer.apiFilterInstance()`.
     * @return A string representing the constructed URL with the API filter parameter included.
     */
    fun viewUrl(apiFilter: FILT = commonContainer.apiFilterInstance()): String =
        urlWithParams(apiFilterParam(apiFilter))

    /**
     * helper to build an api filter parameter in the url string
     */
    fun apiFilterParam(obj: FILT): Pair<String, String> =
        pairParam(key = "apiFilter", serializer = commonContainer.apiFilterSerializer, obj = obj)

    init {
        if (this !is ConfigViewContainer<*, *, *, *>) {
            configViewMap[this.baseUrl] = this
        }
    }
}

/**
 * Configures and returns a `ConfigView` instance using the provided view class, common container, and optional base URL.
 *
 * @param viewKClass The `KClass` reference of the View class to be configured.
 * @param commonContainer The instance of the `ICommon` implementation containing shared parameters and logic.
 * @param baseUrl An optional base URL for the configuration. This is nullable and defaults to `null` if not provided.
 * @return A `ConfigView` instance configured with the specified parameters and types.
 */
@Suppress("unused")
inline fun <V : View<FILT>, reified FILT : IApiFilter<*>> configView(
    viewKClass: KClass<out V>,
    commonContainer: ICommon<FILT>,
    baseUrl: String? = null,
): ConfigView<V, FILT> = object : ConfigView<V, FILT>(
    commonContainer = commonContainer,
    viewKClass = viewKClass,
    _baseUrl = baseUrl,
) {}
