package com.fonrouge.fullStack.layout


import com.fonrouge.base.api.IApiFilter
import com.fonrouge.fullStack.config.ConfigView
import com.fonrouge.fullStack.config.ConfigViewItem
import com.fonrouge.fullStack.config.ConfigViewList
import io.kvision.core.Container
import io.kvision.core.onClick
import io.kvision.dropdown.DropDown
import io.kvision.html.Li

/**
 * Represents an item within a dropdown menu.
 *
 * The `DropItem` class extends the `Li` class and provides functionality for interacting
 * with dropdown menus. It configures the list item to optionally toggle the dropdown
 * when clicked, and allows customization of the item's content, appearance, and behavior.
 *
 * @constructor Creates an instance of `DropItem`.
 * @param text The text to be displayed for the dropdown item.
 * @param rich A flag indicating whether the content should be processed as rich text. Defaults to `false`.
 * @param toggleDropDown A flag specifying whether clicking the item should toggle the nearest parent dropdown. Defaults to `true`.
 * @param className An optional additional CSS class to apply to the dropdown item.
 * @param init A lambda function to allow additional configuration and initialization of the `Li` element.
 */
class DropItem(
    text: String,
    rich: Boolean = false,
    toggleDropDown: Boolean = true,
    className: String? = null,
    init: (Li.() -> Unit) = {}
) : Li(
    content = text,
    rich = rich,
    className = listOfNotNull(className?.takeIf { it.isNotBlank() }, "dropdown-item").toSet().joinToString(" "),
    init = init
) {
    init {
        if (toggleDropDown) {
            setEventListener<Li> {
                click = {
                    toggleNearestParentDropDown()
                }
            }
        }
    }

    private fun toggleNearestParentDropDown() {
        generateSequence(parent) { it.parent }
            .filterIsInstance<DropDown>()
            .firstOrNull()?.toggle()
    }
}

/**
 * Adds a dropdown item to the container.
 *
 * This method creates a `DropItem` instance with the specified text, styling, and behavior.
 * The item can optionally toggle the parent dropdown when clicked and allows customization
 * through an initialization block.
 *
 * @param text The text content of the dropdown item.
 * @param rich A flag indicating whether the text should be processed as rich text. Defaults to `false`.
 * @param toggleDropDown A flag specifying whether the item should toggle the nearest parent dropdown when clicked. Defaults to `true`.
 * @param className An optional additional CSS class for the dropdown item.
 * @param init A lambda function for additional configuration of the dropdown item's properties.
 * @return The created `DropItem` instance.
 */
fun Container.dropItem(
    text: String,
    rich: Boolean = false,
    toggleDropDown: Boolean = false,
    className: String? = null,
    init: (Li.() -> Unit) = {}
): DropItem = DropItem(
    text = text,
    rich = rich,
    toggleDropDown = toggleDropDown,
    className = className,
    init = init
).also(::add)

/**
 * Adds a dropdown item to the container with a specified ID and associated functionality.
 *
 * @param configViewItem The configuration view item that provides label, API filter, and navigation logic.
 * @param id The identifier associated with the item to be dropped.
 * @param apiFilter The API filter instance used for querying, defaulting to the filter instance obtained from the common container.
 * @param target The target where the navigation will open, defaulting to "_blank".
 * @param toggleDropDown Whether the dropdown should toggle visibility, defaulting to false.
 * @param className An optional CSS class to be applied to the dropdown item.
 * @param init An optional initialization block for further customizing the dropdown item's content.
 */
@Suppress("unused")
fun <ID : Any, FILT : IApiFilter<*>> Container.dropItem(
    configViewItem: ConfigViewItem<*, *, ID, *, FILT, *>,
    id: ID,
    apiFilter: FILT = configViewItem.commonContainer.apiFilterInstance(),
    target: String = "_blank",
    toggleDropDown: Boolean = false,
    className: String? = null,
    init: (Li.() -> Unit) = {},
) = dropItem(
    text = configViewItem.label,
    toggleDropDown = toggleDropDown,
    className = className,
) {
    onClick {
        configViewItem.navigateToQueryRead(
            id = id,
            apiFilter = apiFilter,
            target = target
        )
    }
    init(this)
}

/**
 * Adds a dropdown item to the container using a `ConfigViewList` instance for navigation and configuration.
 *
 * This method leverages the provided `ConfigViewList` to configure the dropdown item text and behavior.
 * When clicked, the item navigates to the URL generated by the `ConfigViewList` using the specified API filter
 * and target. Additional customization of the dropdown item is achievable through the initialization block.
 *
 * @param configViewList The `ConfigViewList` instance used to configure the dropdown item and generate navigation behavior.
 * @param apiFilter The API filter instance used for navigation. Defaults to an instance generated by the `ConfigViewList`'s common container.
 * @param target Specifies where to open the URL when the dropdown item is clicked. Defaults to "_blank", which opens in a new tab or window.
 * @param toggleDropDown A flag specifying whether the item should toggle the nearest parent dropdown when clicked. Defaults to `false`.
 * @param className An optional additional CSS class for styling the dropdown item.
 * @param init A lambda function for additional configuration of the dropdown item's properties.
 */
@Suppress("unused")
fun <FILT : IApiFilter<*>> Container.dropItem(
    configViewList: ConfigViewList<*, *, *, *, FILT, *, *>,
    apiFilter: FILT = configViewList.commonContainer.apiFilterInstance(),
    target: String = "_blank",
    toggleDropDown: Boolean = false,
    className: String? = null,
    init: (Li.() -> Unit) = {},
) = dropItem(
    text = configViewList.label,
    toggleDropDown = toggleDropDown,
    className = className,
) {
    onClick {
        configViewList.navigateTo(apiFilter = apiFilter, target = target)
    }
    init(this)
}

/**
 * Creates a drop-down menu item within the container's context, linking it to a specified configuration view and
 * optionally navigating to a corresponding target URL upon selection. The item can also be customized with additional properties.
 *
 * @param configView The configuration view providing the label and API filter instance to associate with the drop-down item.
 * @param apiFilter The API filter instance used for navigation and URL generation. Defaults to the `apiFilterInstance` of the `commonContainer` in the provided `configView`.
 * @param target Specifies the browsing context in which to open the navigation target. Defaults to "_blank", which opens a new tab or window.
 * @param toggleDropDown Indicates whether the drop-down menu should be toggled open or closed when the item is clicked. Defaults to `false`.
 * @param className An optional CSS class to apply to the drop-down item for styling purposes. Defaults to `null`.
 * @param init An optional lambda function providing additional initialization logic for the drop-down menu item.
 */
@Suppress("unused")
fun <FILT: IApiFilter<*>> Container.dropItem(
    configView: ConfigView<*,*,FILT>,
    apiFilter: FILT = configView.commonContainer.apiFilterInstance(),
    target: String = "_blank",
    toggleDropDown: Boolean = false,
    className: String? = null,
    init: (Li.() -> Unit) = {},
) = dropItem(
    text = configView.label,
    toggleDropDown = toggleDropDown,
    className = className
) {
    onClick { configView.navigateTo(apiFilter = apiFilter, target = target) }
    init(this)
}